name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up PHP 8.1+
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # or any version above 8.1
        extensions: mbstring, bcmath, pdo, xml  # Required PHP extensions for Laravel
        coverage: none

    # Install Composer Dependencies
    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist

    # Generate application key
    - name: Generate Application Key
      run: php artisan key:generate

    # Set Directory Permissions
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Run Laravel Migrations
    - name: Run Migrations
      run: php artisan migrate --force

    # Run Tests (PHPUnit)
    - name: Run Tests
      run: vendor/bin/phpunit --testdox
